POST {{apiUrl}}/board
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title";

피실험자 모집
--boundary
Content-Disposition: form-data; name="content";

피실험자 모집합니다~~
--boundary
Content-Disposition: form-data; name="place";

고려대 신공학관
--boundary
Content-Disposition: form-data; name="phoneNum";

010-1234-5678
--boundary
Content-Disposition: form-data; name="school";

고려대학교
--boundary
Content-Disposition: form-data; name="pay";

20000
--boundary
Content-Disposition: form-data; name="time";

20

--boundary
Content-Disposition: form-data; name="dueDate";

2021-08-20

--boundary
Content-Disposition: form-data; name="doDate";

2021-08-10T09:30
--boundary
Content-Disposition: form-data; name="files"; filename="enjoy.png"

< ./../main/resources/mock/images/enjoy.png

###
GET {{apiUrl}}/board/list?page=1&size=10&school=고려대학교&date=2021-08-10
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/board/1
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/board/1
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title";

피실험자 모집 수정
--boundary
Content-Disposition: form-data; name="content";

피실험자 모집합니다 수정~~
--boundary
Content-Disposition: form-data; name="place";

고려대 신공학관 수정
--boundary
Content-Disposition: form-data; name="phoneNum";

010-1234-1234
--boundary
Content-Disposition: form-data; name="school";

연세대학교
--boundary
Content-Disposition: form-data; name="pay";

50000
--boundary
Content-Disposition: form-data; name="time";

120
--boundary
Content-Disposition: form-data; name="dueDate";

2021-08-21
--boundary
Content-Disposition: form-data; name="doDate";

2021-08-25T09:30
--boundary
Content-Disposition: form-data; name="fileChanged";

true
--boundary
Content-Disposition: form-data; name="files"; filename="enjoy.png"

< ./../main/resources/mock/images/enjoy.png
--boundary
Content-Disposition: form-data; name="files"; filename="enjoy2.png"

< ./../main/resources/mock/images/enjoy2.png

###
DELETE {{apiUrl}}/board/1
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/board/like/2
Authorization: {{authorizationToken}}

