POST {{apiUrl}}/board
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "title": "피실험자 모집",
  "content": "피실험자 모집합니다~~",
  "place": "고려대 신공학관",
  "phoneNum": "010-1234-5678",
  "category": "SURVEY",
  "pay": 20000,
  "dueDate": "2021-08-20",
  "doDate": "2021-08-10T09:30:00"
}
